embed_assets: on

javascripts:
  common:
    - public/javascripts/jquery.js
    - public/javascripts/rails.js
    - public/javascripts/core.js

stylesheets:
  global:
    - public/stylesheets/global.css
  main:
    - public/stylesheets/main.css
  admin:
    - public/stylesheets/admin.css
